# INITIAL SETTINGS
train_file: train_split_1_3.csv
val_file: val_split_1_3.csv

# TRAINING SETTINGS
batch_size: 64
num_workers: 0
epochs: 25
lr: 0.003000
weight_decay: 0.000001

# VALIDATION SETTINGS
threshold: 0.500000

# DEVICE CONFIGS
device_count: 1
